feat: integrate background merger
eic/simulation_campaign_hepmc3 pull request #26
Opened 2024-11-06 16:44 UTC by wdconinc

### Briefly, what does this PR introduce?
This injects the background merging into the simulation chain.

2024-11-06 16:49 UTC, wdconinc commented
@veprbl @rahmans1 Consider this a minimum viable product, but unsatisfactory without changes to background merger:
- each file segment will be merged with the same background events, and we can't use the number of events we skip since that doesn't map 1:1 on the background events,
- all backgrounds have to be provided; would prefer this was done automatically based on EBEAMxPBEAM,
- background frequencies are relative to signal frequencies; would prefer to have this be drawn from input weights and cross sections.

2024-11-06 19:13 UTC, wdconinc commented
Tested with e.g.
```
./scripts/run.sh EVGEN/SIDIS/pythia6-eic/1.0.0/10x100/q2_0to1/pythia_ep_noradcor_10x100_q2_0.000000001_1.0_run1.ab.hepmc3.tree.root 1000 2
```

2024-11-06 19:15 UTC, wdconinc commented
Or with e.g.
```
BG1_FREQ=1000 BG1_FILE=root://dtn-eic.jlab.org//work/eic2/EPIC/EVGEN/BACKGROUNDS/BEAMGAS/proton/pythia8.306-1.0/100GeV/pythia8.306-1.0_ProtonBeamGas_100GeV_run082.hepmc3.tree.root ./scripts/run.sh EVGEN/SIDIS/pythia6-eic/1.0.0/10x100/q2_0to1/pythia_ep_noradcor_10x100_q2_0.000000001_1.0_run1.ab.hepmc3.tree.root 1000 2
```

2024-11-06 21:06 UTC, veprbl commented
This is already quite satisfactory. We just need to figure out options presets and file naming to start using this.

> @veprbl @rahmans1 Consider this a minimum viable product, but unsatisfactory without changes to background merger:
> 
>     * each file segment will be merged with the same background events, and we can't use the number of events we skip since that doesn't map 1:1 on the background events,

We can have another intermediate file before merging in which we cutout the subset of *signal* events using abconv, that would make things consistent to the simulation without backgrounds. For *background* events, I agree, we should add an option to adjust position in the loop.

> 
>     * all backgrounds have to be provided; would prefer this was done automatically based on EBEAMxPBEAM,

:+1: 

> 
>     * background frequencies are relative to signal frequencies; would prefer to have this be drawn from input weights and cross sections.

Signal frequency can be calculated from cross section and luminosity. For the first campaigns, it doesn't make sense to use signal frequency mode. The default mode is for one signal event to come at t=0, and that's what we should do because the current version of the EICrecon expects it that way (there are cuts on time). That mode invalidates first part of the statement, because the frequencies, by construction, are only relative to the integration window.

2024-11-06 22:13 UTC, wdconinc commented
> >     * each file segment will be merged with the same background events, and we can't use the number of events we skip since that doesn't map 1:1 on the background events,
> 
> We can have another intermediate file before merging in which we cutout the subset of *signal* events using abconv, that would make things consistent to the simulation without backgrounds. For *background* events, I agree, we should add an option to adjust position in the loop.

I think we can also just pick random events from the input files. Not sure how inefficient it would compared to consecutive, but it would remove the whole skipping aspect.

2025-04-09 15:33 UTC, rahmans1 requested changes
Just needs to add the fourth background source

2025-04-09 15:34 UTC, rahmans1 commented on scripts/run.sh
> +    --bg3Skip ${BG3_SKIP:-0} \
also needs the frequency variable

2025-04-10 13:52 UTC, merged